### ISSUE TITLE
ランダム関数の引数ミス

### ISSUE THREAD

**Issue by uechan16** [MGM-Lion/NKODICE_CUI#4]
https://github.com/MGM-Lion/NKODICE_CUI/blob/17617dcf91800125f976fb8a4ce14173e29eee5a/src/NkoDice.java#L43

r.nextInt(1); ←nextIntに1を入れると0しかランダム関数で生成されないので意味がない
50%の確率で次のifに入りたいならnextInt(2)にするべきです

# 自分のミスです…すみません…

**Comment by MGM-Lion** [comment]
把握しました、修正しときます！

**Comment by MGM-Lion** [comment]
[修正しました！](src/NkoDice.java)
